### PR TITLE
g3: quickcircle: just testing

### PR DESCRIPTION
**Pull request by quesoo**
now you can find it, can u test if it works?

### CODE REVIEW

**Comment by danparidae** [comment]
@quesoo I don't know if I will find some time to test it. but if you want I can provide you a test build in 30 mins

**Comment by quesoo** [comment]
I dont have time either and i dont have a case

Op 27 jul. 2016 5:58 p.m. schreef "Daniel Sikorski" <
notifications@github.com>:

**Comment by danparidae** [comment]
ok, so I will have to look at it later. I will let you know ;)

**Comment by danparidae** [comment]
@quesoo it's still not showing in launcher or anywhere else. I have no idea what it should do but it seems like it doesn't do anything on g3

**Pull request merged**
